//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALI_INNER_EMP_DSG
    {
        public int ID { get; set; }
        public string EMP_NUMBER { get; set; }
        public string DSG_ID { get; set; }
    
        public virtual ALI_DESIGNATION ALI_DESIGNATION { get; set; }
        public virtual ALI_EMPLOYEE ALI_EMPLOYEE { get; set; }
    }
}
