//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALI_DESIGNATION
    {
        public ALI_DESIGNATION()
        {
            this.ALI_INNER_EMP_DSG = new HashSet<ALI_INNER_EMP_DSG>();
        }
    
        public string DSG_ID { get; set; }
        public string DSG_NAME { get; set; }
        public Nullable<int> SALARY { get; set; }
        public string DSG_DEPARTMENT { get; set; }
    
        public virtual ICollection<ALI_INNER_EMP_DSG> ALI_INNER_EMP_DSG { get; set; }
    }
}
