//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M2000_WP_GOODNA_USER_ACCOUNTS
    {
        public string EMP_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public string USR_NAME { get; set; }
        public string PSSWORD { get; set; }
    }
}
