//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEB_API2Entities : DbContext
    {
        public WEB_API2Entities()
            : base("name=WEB_API2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALI_DESIGNATION> ALI_DESIGNATION { get; set; }
        public DbSet<ALI_EMPLOYEE> ALI_EMPLOYEE { get; set; }
        public DbSet<ALI_INNER_EMP_DSG> ALI_INNER_EMP_DSG { get; set; }
        public DbSet<ALI_LOGINDTLS> ALI_LOGINDTLS { get; set; }
    }
}
